apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml

secretGenerator:
  - name: cloudflare-cert-manager
    namespace: cert-manager
    options:
      disableNameSuffixHash: true
    files:
      - secrets/cloudflare/api-token
  - name: cloudflare-external-dns
    namespace: external-dns
    options:
      disableNameSuffixHash: true
    files:
      - secrets/cloudflare/api-token
      - secrets/cloudflare/email

configurations:
  - kustomizeconfig/cert-issuer.yaml
